name: ToolKit
version: ${project.version}
main: cz.qery.toolkit.Main
api-version: '1.20'
authors: [ czQery ]
description: Set of useful tools
website: github.com/czQery/ToolKit

softdepend:
  - dynmap
depend:
  - Apollo-Bukkit

commands:
  toolkit:
    description: Show info about plugin
  crash:
    description: Lag/Crash players game
    permission: toolkit.crash
  skick:
    description: Hax3er kick xDD (Badlion users cannot exit kick screen)
    permission: toolkit.skick
  troll:
    description: Set of troll commands
    permission: toolkit.troll
  crawl:
    description: Allows the player to crawl
    permission: toolkit.crawl
  sit:
    description: Allows the player to sit down
    permission: toolkit.sit
  pinfo:
    description: Show info about player (even their client)
    permission: toolkit.pinfo
  rp:
    description: Set player resource pack
    permission: toolkit.rp
  lunar:
    description: LunarClient tools
    permission: toolkit.lunar
  cmdblock:
    description: Tool for blocking specific commands
    permission: toolkit.commandblock
  vanish:
    description: Hide from other players
    permission: toolkit.vanish
  msg:
    description: Send private message to player
    permission: toolkit.msg
    aliases: [tell, w]
  # Aliases
  gmc:
    description: Switch to CREATIVE mode
    permission: toolkit.gmc
  gms:
    description: Switch to SURVIVAL mode
    permission: toolkit.gms
  gma:
    description: Switch to ADVENTURE mode
    permission: toolkit.gma
  gmsp:
    description: Switch to SPECTATOR mode
    permission: toolkit.gmsp
  spawn:
    description: Teleport to spawn
    permission: toolkit.spawn
  fly:
    description: Allows the player to fly
    permission: toolkit.fly
  wc:
    description: Clear weather
    permission: toolkit.wc
  ic:
    description: Clear inventory
    permission: toolkit.ic

permissions:
  toolkit.crash:
    description: Crash command
  toolkit.crash.bypass:
    description: Bypass crash command
  toolkit.skick:
    description: Skick command
  toolkit.skick.bypass:
    description: Bypass skick command
  toolkit.troll:
    description: Troll command
  toolkit.troll.bypass:
    description: Bypass troll command
  toolkit.crawl:
    description: Crawl command
  toolkit.crawl.other:
    description: Crawl command
  toolkit.sit:
    description: Sit command
  toolkit.sit.other:
    description: Sit command
  toolkit.pinfo:
    description: Pinfo command
  toolkit.rp:
    description: Rp command
  toolkit.lunar:
    description: Lunar command
  toolkit.commandblock:
    description: Cmdblock command
  toolkit.commandblock.bypass:
    description: Bypass cmdblock command
  toolkit.vanish:
    description: Vanish command
  toolkit.msg:
      description: Msg command
  # Aliases
  toolkit.gmc:
    description: Gmc command
  toolkit.gmc.other:
    description: Gmc command
  toolkit.gms:
    description: Gms command
  toolkit.gms.other:
    description: Gms command
  toolkit.gma:
    description: Gma command
  toolkit.gma.other:
    description: Gma command
  toolkit.gmsp:
    description: Gmsp command
  toolkit.gmsp.other:
    description: Gmsp command
  toolkit.spawn:
    description: Spawn command
  toolkit.spawn.other:
    description: Spawn command
  toolkit.fly:
    description: Fly command
  toolkit.fly.other:
    description: Fly command
  toolkit.wc:
    description: Wc command
  toolkit.wc.other:
    description: Wc command
  toolkit.ic:
    description: Clear command
  toolkit.ic.other:
    description: CLear command
  # Other
  toolkit.lunar.staff:
    description: Lunar staff mods