name: ToolKit
version: ${project.version}
main: cz.qery.toolkit.Main
author: czQery
description: Very useful plugin
website: qery.cz

commands:
  crasher:
    description: idk
    aliases: [crash]
  skick:
    description: idk
  toolkit:
    description: idk
  troll:
    description: idk
  crawl:
    description: idk
  sit:
    description: idk

permissions:
  toolkit.crasher:
    description: idk
  toolkit.crasher.bypass:
    description: idk
  toolkit.skick:
    description: idk
  toolkit.skick.bypass:
    description: idk
  toolkit.troll:
    description: idk
  toolkit.troll.bypass:
    description: idk
  toolkit.crawl:
    description: idk
