name: ToolKit
version: ${project.version}
main: cz.qery.toolkit.Main
api-version: 1.18
authors: [ czQery ]
description: Set of useful tools
website: github.com/czQery/ToolKit

commands:
  crash:
    description: Lag/Crash players game
  skick:
    description: Hax3er kick xDD (Badlion users cannot exit kick screen)
  toolkit:
    description: Show info about plugin
  troll:
    description: Set of troll commands
  crawl:
    description: Allows the player to crawl
  sit:
    description: Allows the player to sit down
  pinfo:
    description: Show info about player (even their client)
  rp:
    description: Set player resource pack
  lunar:
    description: LunarClient tools
  cmdblock:
    description: LunarClient tools
  # Aliases
  gmc:
    description: Switch to CREATIVE mode
  gms:
    description: Switch to SURVIVAL mode
  gma:
    description: Switch to ADVENTURE mode
  gmsp:
    description: Switch to SPECTATOR mode

permissions:
  toolkit.crash:
    description: Crash command
  toolkit.crash.bypass:
    description: Bypass crash command
  toolkit.skick:
    description: Skick command
  toolkit.skick.bypass:
    description: Bypass skick command
  toolkit.troll:
    description: Troll command
  toolkit.troll.bypass:
    description: Bypass troll command
  toolkit.crawl:
    description: Crawl command
  toolkit.sit:
    description: Sit command
  toolkit.pinfo:
    description: Pinfo command
  toolkit.rp:
    description: Rp command
  toolkit.lunar:
    description: Lunar command
  toolkit.commandblock:
    description: Cmdblock command
  toolkit.commandblock.bypass:
    description: Bypass cmdblock command
  # Aliases
  toolkit.gmc:
    description: Gmc command
  toolkit.gms:
    description: Gms command
  toolkit.gma:
    description: Gma command
  toolkit.gmsp:
    description: Gmsp command