name: ToolKit
version: ${project.version}
main: cz.qery.toolkit.Main
api-version: 1.16
authors: [ czQery ]
description: Very useful plugin
website: qery.cz
depend: [ ProtocolLib ]

commands:
  crash:
    description: idk
  skick:
    description: idk
  toolkit:
    description: idk
  troll:
    description: idk
  crawl:
    description: idk
  sit:
    description: idk
  pinfo:
    description: idk
  rp:
    description: idk

permissions:
  toolkit.crash:
    description: idk
  toolkit.crash.bypass:
    description: idk
  toolkit.skick:
    description: idk
  toolkit.skick.bypass:
    description: idk
  toolkit.troll:
    description: idk
  toolkit.troll.bypass:
    description: idk
  toolkit.crawl:
    description: idk
  toolkit.sit:
    description: idk
  toolkit.pinfo:
    description: idk
  toolkit.rp:
    description: idk